### ISSUE TITLE
The ascii art is not alignd in Python command line?

### ISSUE THREAD

**Issue by colemanlee** [VaasuDevanS/cowsay-python#2] opened 2019-01-29 13:06 UTC
#### I have an issue about cowsay 2.0 in python，the ascii art is not alignd in Python command line. Like the picture below:
* OS version: Microsoft Windows 10 version 1803
* Python version:Python 3.7.2
* cowsay version: cowsay.about() __version__    ---> 2.0

![pic_0129210255](https://user-images.githubusercontent.com/10258421/51910265-aef35900-2409-11e9-8fdf-b5d59ad9dbd5.jpg)
![pic_0129210307](https://user-images.githubusercontent.com/10258421/51910266-af8bef80-2409-11e9-9270-7fd8fbd7d768.jpg)
![pic_0129210319](https://user-images.githubusercontent.com/10258421/51910268-af8bef80-2409-11e9-8d9a-e3406eb45249.jpg)

**Comment by pjfitzgibbons** [comment] 2019-03-12 14:46
Also cow:
```
  _______________
< BACKUP DATABASE >
  ===============
                    \
                     \
                       ^__^
                       (oo)\_______
                       (__)\       )\/       ||----w |
                           ||     ||
```

**Comment by cs01** [comment] 2019-04-07 00:56
This was from a change I pushed to PyPI. @VaasuDevanS reverted it back to (thanks! :smile:). I have pushed an update to PyPI (v 2.0.3) and also created a [Pull Request](https://github.com/VaasuDevanS/cowsay-python/pull/1) with the changes.

The cause of the problem is that my text editor trims trailing whtiespace when I save, and for some reason this messes up the display of the characters. Ideally this would somehow be fixed in the source code. For now I just turned that setting off and made the change I needed to make.

**Closed** 2019-04-07 23:39 UTC
